<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Camion.aspx.cs" 
Inherits="Ejemplo.Web.Camion" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="~/Styles/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form runat="server">
    <div class="page">
        <div class="header">
            <div class="title">
                <h1>
                    Seccion Administrativa
                </h1>
            </div>
           
            <div class="clear hideSkiplink">
            <asp:Menu ID="NavigationMenu" runat="server" CssClass="menu" EnableViewState="false" IncludeStyleBlock="false" Orientation="Horizontal">
                <Items>

              <asp:MenuItem NavigateUrl="~/SeccionAdministrativa.aspx" Text="Pagina Principal"/>
              <asp:MenuItem NavigateUrl="~/Camion.aspx" Text="Camion" />
              <asp:MenuItem NavigateUrl="~/Camionero.aspx" Text="Camionero" />
              <asp:MenuItem NavigateUrl="~/Empleado.aspx" Text="Empleado" />
              <asp:MenuItem NavigateUrl="~/Parada.aspx" Text="Parada" />
              <asp:MenuItem NavigateUrl="~/Viaje.aspx" Text="Viaje" />
                </Items>
            </asp:Menu>
            </div>
      </div>
    <div class="main">
        <h2>
            Administración de los camiones
        </h2>
        <table>
             <tr>
            <td align="left"> Matricula del camion:
            </td>
            <td>
                <asp:TextBox ID="txtMatricula" MaxLength="50" runat="server"></asp:TextBox>
            </td>
            <td>
                 <asp:RequiredFieldValidator ID="rfvMatricula" runat="server" ErrorMessage="La matricula del camion es obligatorio"
                    ControlToValidate="txtMatricula"></asp:RequiredFieldValidator>
            </td>
        </tr>
             <tr>
            <td align="left"> Marca del camion:
            </td>
            <td>
                <asp:TextBox ID="txtMarca" MaxLength="50" runat="server"></asp:TextBox>
            </td>
            <td>
                 <asp:RequiredFieldValidator ID="rfvMarca" runat="server" ErrorMessage="La marca del camion es obligatorio"
                    ControlToValidate="txtTipoCarga"></asp:RequiredFieldValidator>
            </td>
        </tr>
             <tr>
            <td align="left"> Modelo del camion:
            </td>
            <td>
                <asp:TextBox ID="txtModelo" MaxLength="50" runat="server"></asp:TextBox>
            </td>
            <td>
                 <asp:RequiredFieldValidator ID="rfvModelo" runat="server" ErrorMessage="El modelo del camion es obligatorio"
                    ControlToValidate="txtModelo"></asp:RequiredFieldValidator>
            </td>
        </tr>
             <tr>
            <td align="left"> Año de fabricación:
            </td>
            <td>
                <asp:TextBox ID="txtAñoCam" MaxLength="50" runat="server"></asp:TextBox>
            </td>
            <td>
                 <asp:RequiredFieldValidator ID="rfvAñoCam" runat="server" ErrorMessage="El año de fabricación del camion es obligatorio"
                    ControlToValidate="txtAñoCam"></asp:RequiredFieldValidator>
            </td>
           </tr>
            <tr>
            <td colspan="3" align="left">
                <asp:Label ID="lblResultadoCam" runat="server" ForeColor="Red"></asp:Label>
            </td>
        </tr>
              <tr>
                  <td>
                         <asp:Button ID="btnAgregarCamion" runat="server" Text="Agregar" OnClick="btnAgregarCamion_Click" />
                         <asp:Button ID="btnModificarCamion" runat="server" Text="Modificar" OnClick="btnModificarCamion_Click" Visible="false"/>
                         <asp:GridView ID="grillaCamiones" Width="100%" runat="server" AutoGenerateColumns="true"
                                    ViewStateMode="Enabled" CellPadding="4" ForeColor="#333333" GridLines="None"
                                    AutoGenerateDeleteButton="true" OnRowDeleting="grillaCamiones_RowDeleting" AutoGenerateSelectButton="true"
                                    OnSelectedIndexChanging="grillaCamiones_SelectedIndexChanging" EmptyDataText="No hay datos ingresados"
                                    ShowHeaderWhenEmpty="True">
                                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                                    <EditRowStyle BackColor="#999999" />
                                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                                </asp:GridView>
                      </td>
                </tr>
        </table>
    </div>
    </div>
    </form>
</body>
</html>
