
    <%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Empleados.aspx.cs" Inherits="obligatorio.Presentacion.Empleados" EnableEventValidation="false" %>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
          
    <h1>Gestión de Empleados</h1>
    <form role="form">
      <div class="form-group">
        <label for="InputId">Id</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="InputId" Enabled="False"></asp:TextBox>
      </div>
      <div class="form-group">
        <label for="InputName">Nombre</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="InputName"></asp:TextBox>
      </div>
      <div class="form-group">
        <label for="InputSecondName">Apellido</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="InputSecondName"></asp:TextBox>
      </div>
      <div class="form-group">
        <label for="InputDocument">Cédula</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="InputDocument"></asp:TextBox>
      </div>
      <div class="form-group">
          <label for="InputTelefono">Teléfono</label>
          <asp:TextBox runat="server" CssClass="form-control" ID="InputTelefono"></asp:TextBox>
      </div>
      <div class="form-group">
        <label for="InputUser">Usuario</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="InputUser"></asp:TextBox>
      </div>
      <div class="form-group">
        <label for="InputPass">Contraseña</label>
        <asp:TextBox runat="server" type="password" CssClass="form-control" ID="InputPass"></asp:TextBox> 
          <asp:RadioButton ID="rdbCamionero" runat="server" Text="Camionero" />
          <asp:RadioButton ID="rdbAdministrador" runat="server" Text="Administrador" />
          <asp:Label ID="lblRadioBtn" runat="server"></asp:Label>
          <br />
          <b>
          <br />
          Solo para Camioneros</b>

      </div>
        <div class="form-group">
        <label for="InputPosition">Edad</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="InputEdad"></asp:TextBox>
              <asp:Label ID="lblEdadNotNumber" runat="server"></asp:Label>
      </div>
            <div class="form-group">
        <label for="InputPosition">Tipo de Libreta</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="InputTipoLibreta"></asp:TextBox>
      </div>
      <div class="form-group">
        <label for="InputPosition">Fecha de Vencimiento</label>
        <asp:Calendar runat="server" ID="InputFechaVencimiento"></asp:Calendar>
      </div>
    <div>
&nbsp;<asp:Button ID="btnAlta" runat="server" CssClass="btn-success" Text="Alta" OnClick="btnAlta_Click"/>
&nbsp;&nbsp;&nbsp;
      <asp:Button ID="btnModificar" runat="server" Text="Modificar" OnClick="btnModificar_Click" />
&nbsp;&nbsp;&nbsp;
      <asp:Button ID="btnLimpiar" runat="server" Text="Limpiar" OnClick="btnLimpiar_Click" />
          <br />
          <asp:Label ID="lblDataOutput" runat="server"></asp:Label>
          <br />
        <asp:Label ID="lblC" runat="server"><b>Camioneros</b></asp:Label>
        <asp:GridView ID="grdCamioneros" runat="server" 
                        AutoGenerateColumns="True" AutoGenerateDeleteButton="True" 
                        AutoGenerateSelectButton="True" CellPadding="4" EmptyDataText="No hay datos" GridLines="None" ShowHeaderWhenEmpty="True" 
                        ViewStateMode="Enabled" OnRowDeleting="grdCamioneros_RowDeleting" OnSelectedIndexChanging="grdCamioneros_SelectedIndexChanging">
        </asp:GridView>
          <br />
     </div>    

     <div>
         <asp:Label ID="lblA" runat="server"><b>Administradores</b></asp:Label>
         <asp:GridView ID="grdAdmins" runat="server" 
                        AutoGenerateColumns="True" AutoGenerateDeleteButton="True" 
                        AutoGenerateSelectButton="True" CellPadding="4" EmptyDataText="No hay datos" GridLines="None" ShowHeaderWhenEmpty="True" 
                        ViewStateMode="Enabled" OnRowDeleting="grdAdmins_RowDeleting" OnSelectedIndexChanging="grdAdmins_SelectedIndexChanging">
        </asp:GridView>
     </div>
    </form>
</asp:Content>

