<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Paradas.aspx.cs" Inherits="obligatorio.Presentacion.Paradas" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Label ID="Label1" runat="server" Text="Gestión paradas" Font-Size="Larger"></asp:Label>

    <br />

    <asp:Label ID="Label2" runat="server" Text="Viaje:"></asp:Label>
    <asp:TextBox ID="txtViaje" runat="server"></asp:TextBox>
    <asp:Label ID="lblMissingTrip" runat="server" Text=""></asp:Label>
    <br />
    <asp:Label ID="Label3" runat="server" Text="Razón:"></asp:Label>
    <asp:TextBox ID="txtRazon" runat="server"></asp:TextBox>
    <br />
    <asp:Label ID="Label4" runat="server" Text="Comentario (opcional):"></asp:Label>
    <asp:TextBox ID="txtComentario" runat="server"></asp:TextBox>
    <br />
    <br />
    <asp:Button ID="btnAlta" runat="server" Text="Alta" OnClick="btnAlta_Click" />
    <asp:Button ID="btnModificar" runat="server" Text="Modificar" OnClick="btnModificar_Click" />
    <asp:Button ID="btnLimpiar" runat="server" Text="Limpiar" OnClick="btnLimpiar_Click" />
    <br />
    <br />
    <asp:Label ID="lblDataOutput" runat="server" Text=""></asp:Label>

    <asp:GridView ID="grdParadas" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" CellPadding="4" OnSelectedIndexChanging="grdParadas_SelectedIndexChanging" OnRowDeleting="grdParadas_RowDeleting"></asp:GridView>

</asp:Content>
