<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Viajes.aspx.cs" Inherits="obligatorio.Presentacion.Viajes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <br />
    <b><asp:Label ID="Label1" runat="server" Text="Gestión viajes" Font-Size="Larger"></asp:Label></b>
    <br /> <br />

    <div class="form-group">
        <label for="txtId">Id:</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="txtId" Enabled="false"></asp:TextBox>
      </div>
    <div class="form-group">
        <label for="ddlCamion">Camionero:</label>
        <asp:DropDownList runat="server" CssClass="form-control" ID="ddlCamionero"></asp:DropDownList>
      </div>
    <div class="form-group">
        <label for="ddlCamion">Camión:</label>
        <asp:DropDownList runat="server" CssClass="form-control" ID="ddlCamion"></asp:DropDownList>
      </div>
    <div class="form-group">
        <label for="txtCarga">Carga:</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="txtCarga"></asp:TextBox>
      </div>
    <div class="form-group">
        <label for="txtKilaje">Kilaje:</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="txtKilaje"></asp:TextBox><asp:Label ID="lblMissingKilaje" runat="server" Text=""></asp:Label>
      </div>
    <div class="form-group">
        <label for="txtOrigen">Origen:</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="txtOrigen"></asp:TextBox>
      </div>
    <div class="form-group">
        <label for="txtDestino">Destino:</label>
        <asp:TextBox runat="server" CssClass="form-control" ID="txtDestino"></asp:TextBox>
      </div>
    <div class="form-group">
        <label for="ddlEstado">Estado del Viaje:</label>
        <asp:DropDownList runat="server" CssClass="form-control" ID="ddlEstado">
            <asp:ListItem Text="Propuesto" Value="Propuesto"></asp:ListItem>
            <asp:ListItem Text="En Curso" Value="En Curso"></asp:ListItem>
            <asp:ListItem Text="Parado" Value="Parado"></asp:ListItem>
            <asp:ListItem Text="Finalizado" Value="Finalizado"></asp:ListItem>
        </asp:DropDownList>
      </div>
    <br />
    <asp:Label ID="Label8" runat="server" Text="Fecha de inicio:"></asp:Label>
    <asp:Calendar ID="dtpFechaInicio" runat="server"></asp:Calendar>
    <br />
    <asp:Label ID="Label9" runat="server" Text="Fecha de finalización"></asp:Label>
    <asp:Calendar ID="dtpFechaFin" runat="server"></asp:Calendar>

    <div>
        <br />
        <br />
        <asp:Button ID="btnAlta" Text="Alta" runat="server" OnClick="btnAlta_Click"/>
        <asp:Button ID="btnModificar" Text="Modificar" runat="server" OnClick="btnModificar_Click"/>
        <asp:Button ID="btnLimpiar" Text="Limpiar" runat="server" OnClick="btnLimpiar_Click"/>
        <br />
        <asp:GridView ID="grdViajes" runat="server" 
                        AutoGenerateColumns="True" AutoGenerateDeleteButton="True" 
                        AutoGenerateSelectButton="True" CellPadding="4" EmptyDataText="No hay datos" GridLines="None" ShowHeaderWhenEmpty="True" 
                        ViewStateMode="Enabled" OnRowDeleting="grdViajes_RowDeleting" OnSelectedIndexChanging="grdViajes_SelectedIndexChanging">
        </asp:GridView>
        <br />
        <asp:Label ID="lblDataOutput" runat="server" Text=""></asp:Label>
    </div>

</asp:Content>